### ISSUE TITLE
Review Verifiable Credentials Data Model Specification

### ISSUE THREAD

**Issue by burnburn** [w3c-ccg/community#28] opened 2018-08-14 16:19 UTC
On July 20, 2018 the Verifiable Claims Working Group [asked for this group](https://lists.w3.org/Archives/Public/public-credentials/2018Jul/0045.html) (and others) to give a preliminary review of the Data Model Specification.  As of today the VCWG has heard back from all W3C groups asked for review except this one.

Please review the specification.

We will happily accept any and all reviews but would encourage reviews from people who are new to the specification.

Details are provided in the link above.

**Comment by jandrieu** [comment] 2018-11-30 18:56
Sorry, Dan. This fell under the radar.

**Comment by burnburn** [comment] 2018-11-30 19:13
As long as the CCG is fine with us going to CR when we agree in the VCWG,
no problem :)

**Comment by ChristopherA** [comment] 2018-12-18 17:15
@ipatka has volunteered to take a look over holidays and report back to CCG and to help us with this report.

**Comment by msporny** [comment] 2019-02-02 20:51
Hi @ipatka, Thank you so much for your very thorough review. I'm making the final set of editorial changes to address every comment that you've made in your review.

> One component that lacks definition is the “derived predicate” or “selective disclosure” or “atomized credentials”.

The definition for “derived predicate” went into the specification a while ago, so that is resolved. I just added definitions for "selective disclosure" and changed "atomized credentials" to "data minimization" and added a definition for that. /cc @ChristopherA 

Fixed in 10fc8ad394b7dabc324d26e10096a5b73900ce00.

> Also, the JSON-LD snippets throughout the document contain many @context links to 3rd party sites with machine readable definitions and schema information. This would be a good place to reference content addressed systems like IPFS which have less trust issues.

I have added a section on content integrity protection.

Fixed in 6fb3cc7703b9a9f9aaaf6bdf388ce9fd21ba16e3.

> The [Subject-Holder Relationships](https://w3c.github.io/vc-data-model/#subject-holder-relationships) seems the least defined and it might be better to agree on a simple sharing scheme before defining all of these complex scenarios.

We have received a number of complaints about the complexity of that section. Having scanned through it again, there is only one normative section, so I have moved the entire section to the appendix and linked to it from early in the document for readers that want to know about all of the scenarios.

Fixed in 55f051522ee2238d55057c7ea1b7398a1c06ae16.

> There are many optional properties in the JSON-LD like `evidence` and `refreshing`. All of these supplemental fields need to be included in the proof to show that the issuer actually chose to include these supplemental fields.

I don't track this, those go in the credential and are signed via the proof field. If the issuer didn't want to include any of the optional properties, they don't include the properties. Linked Data Proofs sign the *entire document*. It is not possible to partially sign some properties and not others in a verifiable credential (by design).

> The Privacy Considerations section is very valuable. It would be useful to include guidelines on how to generate and manage these single use subject keys.

Key management is a *very complex* topic and is not suited for this specification. That's way out of scope. I expect other specifications to cover that topic at great length.

> Does the verifiable credential payload need top level versioning? This spec is likely to evolve over time so recipients may need to know what version of the Verifiable Claims spec they need to interpret. > Or is the intention to handle that using the @context fields?

That is handled via the @context fields.

> Is this graph formed by the issuer and given to the holder?

It depends on the use case. The key point is that it doesn't matter how the graph is created, it still represents the same graph of information (either you issue the entire graph at the end in one shot, or you piece it together by merging information graphs from various verifiable credentials.

>  In this example does Pat hold a claim that partially attests some data about a 3rd party Sam? Or is this combined graph intended to show how a verifier would build a model given claims submitted by Pat and Sam separately?

Either can happen. The example doesn't try to get into that depth as it would be introducing the reader to too much too soon. The only thing that section is trying to accomplish is to demonstrate how you can build up an information graph from simple statements. 

> ### Section 3.2 Credentials
> [Verifiable Credentials Data Model 1.0](https://w3c.github.io/vc-data-model/#credentials)
> 
> > A verifiable credential is a set of tamper-evident claims and metadata that cryptographically prove who issued it.
> 
> It is equally important that the holder of the credential can prove they were the original subject or that they can show a chain of custody of the credential. This way a verifier can be sure the entity sending the information is not just forwarding previously received data. This is covered later in [Subject Holder Relationships](https://w3c.github.io/vc-data-model/#subject-holder-relationships) but maybe it should be referenced here earlier.

We're trying to slowly introduce concepts to the reader without overwhelming them with information. What you're talking about here is introduced in the section immediately after 3.2... Section 3.3 Presentation.

> ### Section 4 Trust Model
> [Verifiable Credentials Data Model 1.0](https://w3c.github.io/vc-data-model/#trust-model)
> 
> > The verifier trusts the issuer to issue the credential that it received. To establish this trust, a credential _MUST_ either:
> > 
> > * Include a proof establishing that the issuer generated the credential (that is, it is a verifiable credential)
> > * Have been transmitted in a way clearly establishing that the issuer generated the credential and that the credential was not tampered with in transit or storage. This trust could be weakened depending on the risk assessment of the verifier.
> 
> Unclear how these bullet points are separate conditions. Is it saying in bullet 2 that the issuer is directly sending the credential to the verifier?

Yes, that's one of the things it's saying. It's basically saying, it doesn't matter how the credential gets to the verifier, as long as there is a way for the verifier to determine that it came from an issuer. Digital signatures are one way to do that, but they're not the only way (for example, secure encrypted communication links, object capability-based "access control" are two other possibilities).

> > This trust model differentiates itself from other trust models by ensuring the:
> > 
> > * Issuer and the verifier do not need to trust the repository
> > * Issuer does not need to know or trust the verifier.
> 
> In what trust model does the issuer need to trust the verifier? 

Many of the relying-party flows, such as OpenID Connect, that exist today require that... where the verifier contacts the issuer directly.

> Like the verifier has direct access to issuer’s databases or authentication system?

Yep, which is most systems today that do single sign on.

> ### Section 6.6 Expiration
> > Expiration information for a credential _MAY_ be provided by adding the following property
> > — Section 6.6 Expiration [Verifiable Credentials Data Model 1.0](https://w3c.github.io/vc-data-model/#expiration)
> 
> Is this expiration date arbitrarily chosen by the issuer or should it be based on the subject? The expiration of a verifiable credential may be different than the expiration date of a physical document. For example someone may hold a credential that shows they have a valid unexpired drivers license, but they have to get re-credentialed or refreshed periodically to make sure they have not had their license revoked.

You're highlighting a revocation use case, which the specification covers in Section 6.7: Status.

> ### Section 6.7 Status
> [Verifiable Credentials Data Model 1.0](https://w3c.github.io/vc-data-model/#status)
> 
> > If specified, the value of the credentialStatus property _MUST_ include the:
> > 
> > * id property, which _MUST_ be a URL.
> > * type property, which expresses the credential status type (also referred to as the credential status scheme), which _MUST_ provide enough information to determine the current status of the credential (for example, suspended or revoked).
> 
> ```
>  *”credentialStatus”: {*
> *    “id”: “https://example.edu/status/24”,*
> *    “type”: “CredentialStatusList2017”*
> *  }*,
> ```
> This is unclear. Is id a link to a description of the specific status? 

`id` is a link to the credential status list as described in this WIP specification:

https://w3c-ccg.github.io/vc-csl2017/

> The type references what schema? Shouldn’t type also be a URL?

`type`s are always URLs, which are shortened using JSON-LD syntactic sugar.

> ### Section 6.8 Presentations
> [Verifiable Credentials Data Model 1.0](https://w3c.github.io/vc-data-model/#presentations-0)
> 
> > The example below shows a verifiable presentation that embeds verifiable credentials.
> 
> ```
> ### EXAMPLE 8: Basic structure of a presentation{
>   “@context”: [
>     “https://w3.org/2018/credentials/v1”,
>     “https://example.com/examples/v1”
>   ],
>   “id”: “urn:uuid:3978344f-8596-4c3a-a978-8fcaba3903c5”,
>   “type”: [“VerifiablePresentation”],
>   *”verifiableCredential”: [{ … }],*
> *  “proof”: [{ … }]*
> }
> ```
> Why not have proofs nested in the credentials object instead of in a separate ordered array?

They are, but those proofs are from issuers. The proofs at the presentation layer are by the holder.

> ### Section 7.2 Data Schemas
> [Verifiable Credentials Data Model 1.0](https://w3c.github.io/vc-data-model/#data-schemas)
> 
> ```
> // Example 13
> {
>   “@context”: [
>     “https://w3.org/2018/credentials/v1”,
>     “https://example.org/motorlicense/v1”
>   ],
>   “id”: “http://example.edu/credentials/3732”,
>   “type”: [“VerifiableCredential”, “UniversityDegreeCredential”],
>   “issuer”: “https://example.edu/issuers/14”,
>   “issuanceDate”: “2010-01-01T19:23:24Z”,
>   “credentialSubject”: {
>     “id”: “did:example:ebfeb1f712ebc6f1c276e12ec21”,
>     “degree”: {
>       “type”: “BachelorDegree”,
>       “name”: “Bachelor of Science in Mechanical Engineering”
>     }
>   },
>   *”credentialSchema”: {*
> *    “id”: “https://example.org/motorlicense/proof-of-age.json”,*
> *    “type”: “JsonSchemaValidator2018”*
> *  }*,
>   “proof”: { … }
> }
> ```
> Why is `credentialSchema` referencing proof-of-age but the `credentialSubject` references a University Degree?

That is a bug, thank you. Fixed in the latest spec.

> ```
> // Example 14
> {
>   “@context”: [
>     “https://w3.org/2018/credentials/v1”,
>     “https://example.org/motorlicense/v1”
>   ],
>   “id”: “http://example.edu/credentials/3732”,
>   “type”: [“VerifiableCredential”, “UniversityDegreeCredential”],
>   “issuer”: “https://example.edu/issuers/14”,
>   “issuanceDate”: “2010-01-01T19:23:24Z”,
>   “credentialSubject”: {
>     “id”: “did:example:ebfeb1f712ebc6f1c276e12ec21”,
>     “degree”: {
>       “type”: “BachelorDegree”,
>       “name”: “Bachelor of Science in Mechanical Engineering”
>     }
>   },
>   *”credentialSchema”: {*
> *    “id”: “https://example.org/motorlicense/proof-of-age.zkp”,*
> *    “type”: “ZkpExampleSchema2018”*
> *  }*,
>   “proof”: { … }
> }
> ```
> Is the ZK proof embedded in the payload or linked to be downloaded from example.org?

It is linked and needs to be downloaded from example.org.

> ### Section 7.3 Refreshing
> [Verifiable Credentials Data Model 1.0](https://w3c.github.io/vc-data-model/#refreshing)
> What is the benefit of a refreshed credential over simply issuing a new one? Is this complexity needed?

The process of refreshing a credential *is* issuing a new one. The RefreshService just tells the holder where to go to get a new credential once their current one expires.

> ### Section 7.5 Terms of Use
> [Verifiable Credentials Data Model 1.0](https://w3c.github.io/vc-data-model/#terms-of-use)
> Great idea to request verifier does not store/ archive received credentials. But what is the recommended way to enforce or audit this?

There is no way to enforce or audit it unless you have access to the verifiers systems. There is now language in the spec highlighting this:

>  If the recipient (a holder or verifier) is not willing to adhere to the specified terms of use, then they do so on their own responsibility and might incur legal liability if they violate the stated Terms of Use.

> ### Section 7.8 Disputes
> [Verifiable Credentials Data Model 1.0](https://w3c.github.io/vc-data-model/#disputes)
> The hardest thing about disputes is deciding on the trusted repo in which to store them. Some of the dispute types are unnecessary. 

The entire data model assumes an "open world" where anyone can say anything about anything. Thus, there is no "one trusted repo" or "trusted repos". There are just statements that are made by issuers about subjects. Some of those issuers are people, others are organizations, and its up to verifiers to determine who they trust. We provide disputes and status to enable both sides to state things (instead of just having a lop-sided power dynamic such as what exists today).

> If the subject disputes a claim from the issuer they should just throw it out and get a new, valid one. 

The subject can't do this if the issuer is lying and publishing a credential to the general public.

> Also, what is the difference between the dispute process and the Revocation system referenced in section 9.8 [Verifiable Credentials Data Model 1.0](https://w3c.github.io/vc-data-model/#revocation)?

Revocation is something that issuers do.

Disputes are something that subjects do.

> ### Section 9.6 Issuance
> > [Verifiable Credentials Data Model 1.0](https://w3c.github.io/vc-data-model/#issuance)
> > The issuanceDate _MUST_ be within an expected range for the verifier. For example, a verifier can ensure that the issuance date of a verifiable credential is not in the future.
> 
> If the proof involves an on chain registry the issuance date should also be validated against the transaction timestamp. Whichever way it gets implemented the issuance date needs to be validated by the proof.

Yes, that is one way that issuance date can be checked. Others would be getting a digitally signed proof from a trusted atomic clock service, tangling your proof on other blockchains, using something like Open Timstamps or Chainpoint, etc.

**Comment by msporny** [comment] 2019-02-02 20:53
I believe that all review comments have resulted in answers or changes to the specification. From an editorial standpoint, I think we're done here. @ipatka, please re-open the issue if you disagree.

**Closed by msporny** 2019-02-02 20:53 UTC
Labels: action: ccg, action: review next, meeting: future
